# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  matrix:
  - R_VERSION: 4.2.3
    R_ARCH: x64
    BIOC_USE_DEVEL: FALSE
    USE_RTOOLS: TRUE
    PKGTYPE: binary

branches:
  only:
    - main

build_script:
  - Rscript -e install.packages('https://cloud.r-project.org/bin/windows/contrib/4.2/Matrix_1.6-5.zip',type='source',repos=NULL)
  - Rscript -e install.packages('https://cloud.r-project.org/bin/windows/contrib/4.2/nloptr_2.0.3.zip',type='source',repos=NULL)
  - Rscript -e install.packages('https://cloud.r-project.org/bin/windows/contrib/4.2/RCurl_1.98-1.14.zip',type='source',repos=NULL)
  - Rscript -e install.packages('https://cloud.r-project.org/bin/windows/contrib/4.2/bitops_1.0.7.zip',type='source',repos=NULL)
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc GENESIS
  - travis-tool.sh install_github xihaoli/STAAR

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs
