[workspace]
channels = ["conda-forge", "bioconda"]
name = "MetaSTAAR"
platforms = ["linux-64"]

[tasks]

[dependencies]
bioconductor-genesis = ">=2.36.0,<3"
blas = { version = "*", build = "*mkl*" }
r-compquadform = ">=1.4.4,<2"
"r-data.table" = ">=1.17.6,<2"
r-dplyr = ">=1.1.4,<2"
r-expm = ">=1.0_0,<2"
r-foreach = ">=1.5.2,<2"
r-mass = ">=7.3_64,<8"
r-matrix = ">=1.7_3,<2"
r-rcpp = ">=1.1.0,<2"
r-rcpparmadillo = ">=14.4.2_1,<15"
zlib = ">=1.3.1,<2"
